server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,text/plain,application/javascript
    min-response-size: 1024
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
logging:
  level:
    com.example.optimized: INFO

spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: sa
  datasource:
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2-console
